version: "3.8"
services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:8
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  npm:
    build:
      context: ./dockerfiles
      dockerfile: npm.dockerfile
    volumes:
      - ./src:/var/www/html

